apiVersion: v1
kind: Service
metadata:
  name: ml-app-service
  labels:
    app: ml-app
spec:
  type: NodePort  # Change to LoadBalancer if running in cloud
  selector:
    app: ml-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30080   # optional; Kubernetes may assign if omitted
